language: python

python:
  - "3.6"
arch: amd64
os: linux
dist: focal

script:
    # Update repository version
  - sed -i -e "s/__version__ =.*/__version__ = \"$(git describe --tags)\"/" siriushlacon/__init__.py
  - cat siriushlacon/__init__.py | grep 'version\|author'

deploy:
  skip_cleanup: true
  provider: pypi
  username: __token__
  password:
    secure: "tYvPD3MnKrxDnWpOOg6Aa2o7Je9dsPfAWsqjGxUtq+ViLU6aZ91AB6B2/IG6dlksiXfa9DexV/PFHdsCIcQVbft5nhcO7G8Wy2vJ4/8XWAob++c7wiHO9yf9mjdE/5l8kZJe9V5QfpNVblEh8X7FuIJKuy3PVo5VEMQMJzibB1pYf8ZcJ/H3aOqqpx+LuqpZ5OL+trDmS+PhDo54CROOW8hSFvRTMrM3ZsV3ZThrIru+GdNhlMDjfA70zX39Mm6r0dW7VK3vBTK9Pj+rfSMfitUFABiNGlcd6r7fuLUfwCR7wqdTSpoEXWZl1eS3T7dTXY6a2muYSHv0vXUfG7Q05yKGU8/8QZbRWoOhP0TYs9SxDw1bz5RxbkpyB7jvhK40aCzkg03QYq4/TXwgV9pRs8zVeuMo13lOJbhc73Q5uAM+NjXQIIg26dwK9xhbNH6sdn3+P/aAda3AaShASU7ot4rVbaog1GVizIsSA79NqwcY20PKwpHzPnw8kB+1jxpiOpZdzVnLYUOq3hYVeOaExyxY+2w3HyIeAOnfkAGyWXEeoVFT5OA2OqzUnD8/Yrdx+94CZCOShE3CcqMwTQPF67ZShtDLjpr/ACC+9MKNYkqp+QD1npdLu06gLc8kyHGob5sy13gAJNZkSt7Zj+/7nQGTqmPQDUwAJaBDZMrJot4="
  on:
    tags: true
    branch: master

after_deploy:
  - sleep 30
  - python -m pip search siriushlacon
