name: Test and Coverage

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate coverage report
        run: |
          pip install coverage
          pip install -e . -v
          coverage run -m unittest discover
          coverage xml
          coverage report

#     - name: Upload coverage to Codecov
#       uses: codecov/codecov-action@v2
#       with:
#         #         directory: ./coverage/reports/
#         #         env_vars: OS,PYTHON
#         #         path_to_write_report: ./coverage/codecov_report.txt
#         #         token: ${{ secrets.CODECOV_TOKEN }}
#         fail_ci_if_error: true
#         files: ./coverage.xml
#         flags: unittests
#         name: mailpy-codecov
#         verbose: true
